# Generated by Django 3.0.5 on 2021-03-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20210312_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payment_type',
            field=models.CharField(choices=[('qiwi', 'Киви'), ('yoomoney', 'Юмани'), ('card', 'Карта')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
