# Generated by Django 3.0.5 on 2021-03-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_remove_partner_all_referrals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарезервировано')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to='partners.Partner', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Партнерский кошелек',
                'verbose_name_plural': 'Партнерские кошельки',
            },
        ),
    ]
