# Generated by Django 3.0.5 on 2021-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210318_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payment_type',
            field=models.CharField(choices=[('qiwi', 'Киви'), ('yoomoney', 'Юmoney'), ('card', 'Карта')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
