# Generated by Django 3.0.5 on 2021-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210326_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Пригласительная ссылка'),
        ),
    ]
