version: '3'

services:
  django:
    build: .
    container_name: django 
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./db/redis/:/var/lib/redis
    ports:
      - 6379:6379
