# Generated by Django 3.0.5 on 2022-12-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221202_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramchannel',
            old_name='telegram_users',
            new_name='telegram_user',
        ),
    ]
