# Generated by Django 3.0.5 on 2022-12-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0097_auto_20221129_1745'),
        ('api', '0006_auto_20221202_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_subscribe_page',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channel', to='subscribe_pages.TelegramSubscribePage'),
            preserve_default=False,
        ),
    ]
