# Generated by Django 3.0.5 on 2022-12-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_telegramchannel_telegram_subscribe_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchannel',
            name='telegram_subscribe_page',
        ),
    ]
