# Generated by Django 3.0.5 on 2022-12-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_telegramchannel_telegram_subscribe_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='api.TelegramUser'),
        ),
    ]
