# Generated by Django 3.0.5 on 2021-03-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=30, verbose_name='Отчисления')),
                ('earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработано')),
                ('clicks', models.IntegerField(default=0, verbose_name='Кликов')),
                ('active_referrals', models.ManyToManyField(related_name='active_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Активные пользователи')),
                ('all_referrals', models.ManyToManyField(related_name='all_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Всего активных пользователей')),
                ('referrals', models.ManyToManyField(related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённые')),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL, verbose_name='Пригласитель')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Пригласительная ссылка')),
                ('earned', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработано')),
                ('clicks', models.IntegerField(default=0, verbose_name='Клики')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners.Partner', verbose_name='Пригласитель')),
                ('registered', models.ManyToManyField(related_name='registered', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировано')),
            ],
        ),
    ]
