# Generated by Django 3.0.5 on 2021-03-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20210309_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработано'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='partners.Partner', verbose_name='Пригласитель'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='registered',
            field=models.ManyToManyField(blank=True, related_name='registered', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировано'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='partners.Partner', verbose_name='Пригласитель'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payment_type',
            field=models.CharField(choices=[('qiwi', 'Киви'), ('yandex', 'Юмани'), ('card', 'Карта')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
