# Generated by Django 3.0.5 on 2021-03-12 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0003_auto_20210312_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Возможно удалить'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='active_referrals',
            field=models.ManyToManyField(blank=True, related_name='active_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Активные пользователи'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='all_referrals',
            field=models.ManyToManyField(blank=True, related_name='all_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Всего активных пользователей'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённые'),
        ),
    ]
