# Generated by Django 3.0.5 on 2021-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20210316_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='all_referrals',
        ),
    ]
