# Generated by Django 3.0.5 on 2021-03-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partnerpocket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ('-created',), 'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
        migrations.AlterField(
            model_name='payout',
            name='pay_outed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
