# Generated by Django 3.0.5 on 2021-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20210329_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='pay_outed',
            new_name='is_pay_outed',
        ),
        migrations.AddField(
            model_name='partnerpocket',
            name='pay_outed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплачено'),
        ),
    ]
