# Generated by Django 3.0.5 on 2021-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20210408_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payment_type',
            field=models.CharField(choices=[('yoomoney', 'Юmoney'), ('card', 'Карта')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
