# Generated by Django 3.0.5 on 2021-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201214_1655'),
    ]

    operations = [
    ]
