# Generated by Django 3.0.5 on 2021-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bot_all_requests'),
    ]

    operations = [
    ]
