# Generated by Django 3.0.5 on 2021-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bot_success_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_referral',
            field=models.BooleanField(default=False, verbose_name='Реферал'),
        ),
    ]
