# Generated by Django 3.0.5 on 2021-04-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210408_0701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
