# Generated by Django 3.0.5 on 2021-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_promocode'),
    ]

    operations = [
    ]
