# Generated by Django 3.0.5 on 2021-11-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210410_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocket',
            options={'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Верификационный UUID'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
