# Generated by Django 3.0.5 on 2022-02-20 09:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211228_1048'),
    ]

    operations = [
    ]
