# Generated by Django 3.0.5 on 2022-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_subscribe_pages', '0002_auto_20221207_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время подписки'),
        ),
    ]
