# Generated by Django 3.0.5 on 2020-12-03 10:52

import apps.subscribe_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostPerSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Cost per subscriber',
                'verbose_name_plural': 'Cost per subscribers',
            },
        ),
        migrations.CreateModel(
            name='InstagramCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=250, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagrams',
            },
        ),
        migrations.CreateModel(
            name='InstagramStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('views', models.BigIntegerField(default=0, verbose_name='Views')),
                ('subscribers', models.BigIntegerField(default=0, verbose_name='Subscribers')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ('subscribe_page',),
            },
        ),
        migrations.CreateModel(
            name='InstagramSubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=60, verbose_name='Page name')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Page url')),
                ('page_photo', models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.InstagramSubscribePage.get_page_photo_path, verbose_name='Page photo')),
                ('instagram_username', models.CharField(max_length=40, null=True, verbose_name='Instagram login')),
                ('instagram_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram name')),
                ('instagram_avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram avatar')),
                ('title', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('button_text', models.CharField(blank=True, default='ПОЛУЧИТЬ', max_length=30, null=True, verbose_name='Text on button')),
                ('is_timer_active', models.BooleanField(default=False, verbose_name='Countdown timer')),
                ('timer_time', models.IntegerField(default=180, verbose_name='Countdown timer time')),
                ('facebook_pixel', models.TextField(blank=True, null=True, verbose_name='Facebook pixel')),
                ('popup_title', models.CharField(default='Успешно', max_length=50, null=True, verbose_name='Title')),
                ('popup_text', models.TextField(default='Можете получить материал, нажав по кнопке ниже.', null=True, verbose_name='Text')),
                ('popup_button_url', models.CharField(max_length=255, null=True, verbose_name='Button url')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscribe Page',
                'verbose_name_plural': 'Subscribe Pages',
            },
        ),
        migrations.CreateModel(
            name='InstagramSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('instagram_username', models.CharField(max_length=50, verbose_name='Instagram login')),
                ('subscribe_to', models.ManyToManyField(related_name='subscribers', to='subscribe_pages.InstagramSubscribePage')),
                ('views', models.ManyToManyField(related_name='views', to='subscribe_pages.InstagramSubscribePage')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
