# Generated by Django 3.0.5 on 2020-12-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0005_auto_20201208_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramstatistic',
            name='crt',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CRT'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='timer_text',
            field=models.CharField(default='Материал станет недоступным через:', max_length=39, verbose_name='Timer text'),
        ),
    ]
