# Generated by Django 3.0.5 on 2021-01-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0009_instagramsubscribepage_tiktok_pixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='tiktok_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok пиксель'),
        ),
    ]
