# Generated by Django 3.0.5 on 2021-02-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0015_domain_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='added',
        ),
    ]
