# Generated by Django 3.0.5 on 2021-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0021_bgcolor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgcolor',
            name='slug',
            field=models.CharField(default='0', max_length=255, verbose_name='Название цвет'),
            preserve_default=False,
        ),
    ]
