# Generated by Django 3.0.5 on 2021-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0022_bgcolor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgcolor',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Название цвет'),
        ),
    ]
