# Generated by Django 3.0.5 on 2021-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0029_auto_20210408_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Ссылка подписной страницы'),
        ),
    ]
