# Generated by Django 3.0.5 on 2021-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0037_instagramsubscribepage_roistat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='already_subscribed_text',
            field=models.CharField(default='Я уже подписался', max_length=255, verbose_name='Текст "Я уже подписался" под кнопкой'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='error_text',
            field=models.CharField(default='Аккаунт не найден!', max_length=255, verbose_name='Текст "Аккаунт не найден"'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='not_yet_subscribed',
            field=models.CharField(default='Я еще не подписался', max_length=255, verbose_name='Текст "Я еще не подписался" под кнопкой'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='search_text',
            field=models.CharField(default='Поиск аккаунта...', max_length=255, verbose_name='Текст "Поиск аккаунта..."'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='subscribe_button',
            field=models.CharField(default='Подписаться', max_length=255, verbose_name='Текст "Подписаться" на кнопке'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='subscribed_button',
            field=models.CharField(default='Подписался', max_length=255, verbose_name='Текст "Я подписался" на кнопке'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='success_text',
            field=models.CharField(default='Аккаунт найден!', max_length=255, verbose_name='Текст "Аккаунт найден"'),
        ),
    ]
