# Generated by Django 3.0.5 on 2021-10-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0037_instagramsubscribepage_roistat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfSubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('subscribe_pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='subscribe_pages.InstagramSubscribePage', verbose_name='Страницы')),
            ],
            options={
                'verbose_name': 'Группа страниц',
                'verbose_name_plural': 'Группы страниц',
            },
        ),
    ]
