# Generated by Django 3.0.5 on 2021-11-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0039_auto_20211026_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupofsubscribepage',
            name='subscribe_pages',
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribe_pages.GroupOfSubscribePage', verbose_name='Группа страниц'),
        ),
        migrations.AlterField(
            model_name='groupofsubscribepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_pages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
