# Generated by Django 3.0.5 on 2021-11-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0040_auto_20211108_1406'),
        ('subscribe_pages', '0040_auto_20211101_1211'),
    ]

    operations = [
    ]
