# Generated by Django 3.0.5 on 2022-01-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0051_auto_20211223_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl',
            field=models.BooleanField(default=False, verbose_name='SSL сертификат'),
        ),
    ]
