# Generated by Django 3.0.5 on 2022-03-24 23:43

import apps.subscribe_pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0052_auto_20220129_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKSubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=60, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Ссылка подписной страницы')),
                ('page_photo', models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.VKSubscribePage.get_page_photo_path, verbose_name='Page photo')),
                ('title', models.CharField(max_length=60, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('button_text', models.CharField(default='ПОЛУЧИТЬ', max_length=30, verbose_name='Текст на кнопке')),
                ('vk_group_id', models.CharField(max_length=70, null=True, verbose_name='ID группы ВК')),
                ('timer_text', models.CharField(blank=True, default='Материал станет недоступным через:', max_length=39, null=True, verbose_name='Текст на таймере')),
                ('is_timer_active', models.BooleanField(default=False, verbose_name='Таймер обратного отсчёта')),
                ('timer_time', models.IntegerField(default=180, verbose_name='Время таймера (в секундах)')),
                ('facebook_pixel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook пиксель')),
                ('tiktok_pixel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok пиксель')),
                ('vk_pixel', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВК пиксель')),
                ('yandex_pixel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Яндекс метрика')),
                ('roistat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Roistat ID')),
                ('ctr', models.FloatField(blank=True, default=0, null=True, verbose_name='CTR')),
                ('success_title', models.CharField(default='Успешно', max_length=50, verbose_name='Заголовок')),
                ('success_text', models.TextField(default='Можете получить материалы, нажав по кнопке ниже.', verbose_name='Текст')),
                ('success_button_url', models.TextField(null=True, verbose_name='Ссылка кнопки')),
                ('success_button_text', models.CharField(default='ПОЛУЧИТЬ МАТЕРИАЛЫ', max_length=19, verbose_name='Текст на кнопке')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('created', models.BooleanField(default=False, verbose_name='Создано')),
                ('bg_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_subscribe_pages', to='subscribe_pages.BGColor', verbose_name='Цвет фона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_subscribe_pages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ВК Подписная страница',
                'verbose_name_plural': 'ВК Подписные страницы',
            },
        ),
        migrations.CreateModel(
            name='VKStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('subscribers', models.BigIntegerField(default=0, verbose_name='Подписки')),
                ('ctr', models.FloatField(blank=True, default=0, null=True, verbose_name='CTR')),
                ('vk_subscribe_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='subscribe_pages.VKSubscribePage', verbose_name='ВК Страница')),
            ],
            options={
                'verbose_name': 'ВК Статистика',
                'verbose_name_plural': 'ВК Статистики',
                'ordering': ('vk_subscribe_page',),
            },
        ),
    ]
