# Generated by Django 3.0.5 on 2022-03-26 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0053_vkstatistic_vksubscribepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_user_id', models.BigIntegerField(verbose_name='ID пользователя ВК')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамиллия')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=7, null=True, verbose_name='Пол')),
                ('photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания в сервисе')),
            ],
            options={
                'verbose_name': 'ВК Подписчик',
                'verbose_name_plural': 'ВК Подписчики',
            },
        ),
        migrations.CreateModel(
            name='VKSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Подписался')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('vk_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribe_pages.VKSubscribePage', verbose_name='ВК подписная страница')),
                ('vk_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribe_pages.VKSubscriber', verbose_name='ВК подписчик')),
            ],
            options={
                'verbose_name': 'ВК Подписка',
                'verbose_name_plural': 'ВК Подписки',
            },
        ),
    ]
