# Generated by Django 3.0.5 on 2022-03-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0056_auto_20220331_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vksubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_subscribe_pages', to='subscribe_pages.VKGroupOfSubscribePage', verbose_name='Группа ВК страниц'),
        ),
    ]
