# Generated by Django 3.0.5 on 2022-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0058_auto_20220406_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vksubscription',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата подписки'),
        ),
    ]
