# Generated by Django 3.0.5 on 2022-04-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0062_auto_20220418_1547'),
        ('subscribe_pages', '0062_auto_20220418_2204'),
    ]

    operations = [
    ]
