# Generated by Django 3.0.5 on 2022-11-09 17:45

import apps.subscribe_pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0065_telegramsubscribepage_present_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscribepage',
            options={'verbose_name': 'Подписная страница', 'verbose_name_plural': 'Подписные страницы'},
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='present_url',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='telegram_bot_url',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='telegram_channel_id',
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='already_subscribed_text',
            field=models.CharField(default='Я уже подписался', max_length=255, verbose_name='Текст "Я уже подписался" под кнопкой'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='bg_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribe_pages', to='subscribe_pages.BGColor', verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ', max_length=30, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='ctr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CTR'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribe_pages', to='subscribe_pages.Domain', verbose_name='Домен'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='enter_login_placeholder',
            field=models.CharField(default='введите ваш логин', max_length=255, verbose_name='Текст "Введите ваш логин"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='error_text',
            field=models.CharField(default='Аккаунт не найден!', max_length=255, verbose_name='Текст "Аккаунт не найден"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook пиксель'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='follower_count',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='following_count',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribe_pages', to='subscribe_pages.GroupOfSubscribePage', verbose_name='Группа страниц'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='help_text',
            field=models.CharField(default='Здесь находится логин', max_length=255, verbose_name='Текст "Здесь находиться логин" (подсказка)'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='instagram_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.TelegramSubscribePage.get_instagram_avatar_path, verbose_name='Аватарка Instagram'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в Instagram'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='instagram_username',
            field=models.CharField(max_length=40, null=True, verbose_name='Ник в Instagram'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='is_timer_active',
            field=models.BooleanField(default=False, verbose_name='Таймер обратного отсчёта'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='media_count',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='not_yet_subscribed',
            field=models.CharField(default='Я еще не подписался', max_length=255, verbose_name='Текст "Я еще не подписался" под кнопкой'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='page_name',
            field=models.CharField(default='hello page', max_length=60, verbose_name='Название страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='page_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.TelegramSubscribePage.get_page_photo_path, verbose_name='Page photo'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='popup_button_text',
            field=models.CharField(default='ПОЛУЧИТЬ МАТЕРИАЛЫ', max_length=19, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='popup_button_url',
            field=models.TextField(null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='popup_text',
            field=models.TextField(default='Можете получить материалы, нажав по кнопке ниже.', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='popup_title',
            field=models.CharField(default='Успешно', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='precheck_subscribe_text',
            field=models.CharField(default='Введите ваш логин инстаграма для проверки подписки', max_length=255, verbose_name='Текст "Введите ваш логин инстаграма для проверки подписки"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='presearch_text',
            field=models.CharField(default='После подписки вернись на эту страницу для подтверждения', max_length=255, verbose_name='Текст "После подписки вернись на эту страницу для подтверждения"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='presubscribe_text',
            field=models.CharField(default='Подпишись на мой инстаграм и ссылка для скачивания материалов станет доступна', max_length=255, verbose_name='Текст перед подпиской'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='roistat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Roistat ID'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='search_text',
            field=models.CharField(default='Поиск аккаунта...', max_length=255, verbose_name='Текст "Поиск аккаунта..."'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='search_time_text',
            field=models.CharField(default='Это может занять до 20 секунд', max_length=255, verbose_name='Текст "Это может занять до 20 секунд"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='show_subscribers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='single_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True, verbose_name='Ссылка подписной страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='subscribe_button',
            field=models.CharField(default='Подписаться', max_length=255, verbose_name='Текст "Подписаться" на кнопке'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='subscribed_button',
            field=models.CharField(default='Подписался', max_length=255, verbose_name='Текст "Я подписался" на кнопке'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='success_text',
            field=models.CharField(default='Аккаунт найден!', max_length=255, verbose_name='Текст "Аккаунт найден"'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='tiktok_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok пиксель'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='timer_text',
            field=models.CharField(blank=True, default='Материал станет недоступным через:', max_length=39, null=True, verbose_name='Текст на таймере'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='timer_time',
            field=models.IntegerField(default=180, verbose_name='Время таймера (в секундах)'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='title',
            field=models.CharField(max_length=60, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='vk_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ВК пиксель'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='yandex_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Яндекс метрика'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_subscribe_pages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='TelegramGroupOfSubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('can_delete', models.BooleanField(default=True, verbose_name='Можно удалить')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group_of_pages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа Telegram страницы',
                'verbose_name_plural': 'Группы Telegram страниц',
            },
        ),
    ]
