# Generated by Django 3.0.5 on 2022-11-09 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0066_auto_20221109_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupofsubscribepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_group_of_pages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribe_pages', to='subscribe_pages.TelegramGroupOfSubscribePage', verbose_name='Группа страниц'),
        ),
    ]
