# Generated by Django 3.0.5 on 2022-11-10 15:54

import apps.subscribe_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0069_remove_telegramsubscribepage_single_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='instagram_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.TelegramSubscribePage.get_instagram_avatar_path, verbose_name='Аватарка Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='instagram_username',
            field=models.CharField(max_length=40, null=True, verbose_name='Ник в Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='precheck_subscribe_text',
            field=models.CharField(default='Введите ваш логин телеграма для проверки подписки', max_length=255, verbose_name='Текст "Введите ваш логин телеграма для проверки подписки"'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='presubscribe_text',
            field=models.CharField(default='Подпишись на мой телеграм и ссылка для скачивания материалов станет доступна', max_length=255, verbose_name='Текст перед подпиской'),
        ),
    ]
