# Generated by Django 3.0.5 on 2022-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0070_auto_20221110_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='можете получить материалы, нажав на кнопку ниже', max_length=30, verbose_name='Текст'),
        ),
    ]
