# Generated by Django 3.0.5 on 2022-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0078_auto_20221110_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ', max_length=30, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='title',
            field=models.CharField(max_length=60, null=True, verbose_name='Заголовок'),
        ),
    ]
