# Generated by Django 3.0.5 on 2022-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0081_remove_telegramsubscribepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='message_after_getting_present',
            field=models.CharField(default='', max_length=2000, verbose_name='Сообщение при выдаче подарка'),
            preserve_default=False,
        ),
    ]
