# Generated by Django 3.0.5 on 2022-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0084_auto_20221111_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
