# Generated by Django 3.0.5 on 2022-11-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0086_remove_telegramsubscribepage_precheck_subscribe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramsubscribepage',
            old_name='instagram_name',
            new_name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='already_subscribed_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='enter_login_placeholder',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='error_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='not_yet_subscribed',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='presearch_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='search_time_text',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='subscribe_button',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='subscribed_button',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='success_text',
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='is_linked',
            field=models.BooleanField(default=False, verbose_name='Превязан'),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='telegram_bot_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
