# Generated by Django 3.0.5 on 2022-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0094_auto_20221125_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramsubscribepage',
            old_name='bot_button_text',
            new_name='button_text',
        ),
        migrations.RenameField(
            model_name='telegramsubscribepage',
            old_name='bot_button_url',
            new_name='button_url',
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vksubscribepage',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок'),
        ),
    ]
