# Generated by Django 3.0.5 on 2022-12-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0098_telegramsubscribepage_telegram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_chat_id',
            field=models.CharField(default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_username',
            field=models.CharField(default='eeee', max_length=100),
            preserve_default=False,
        ),
    ]
