# Generated by Django 3.0.5 on 2020-12-06 08:20

import apps.subscribe_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0002_auto_20201203_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook pixel'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='instagram_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.subscribe_pages.models.InstagramSubscribePage.get_instagram_avatar_path, verbose_name='Instagram avatar'),
        ),
    ]
