# Generated by Django 3.0.5 on 2020-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0003_auto_20201206_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='crt',
            field=models.FloatField(default=0, verbose_name='CRT'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ', max_length=30, verbose_name='Text on button'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='popup_text',
            field=models.TextField(default='Можете получить материал, нажав по кнопке ниже.', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='popup_title',
            field=models.CharField(default='Успешно', max_length=50, verbose_name='Title'),
        ),
    ]
