# Generated by Django 3.0.5 on 2020-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0004_auto_20201208_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='crt',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CRT'),
        ),
    ]
