# Generated by Django 3.0.5 on 2020-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0007_auto_20201212_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramstatistic',
            name='crt',
        ),
        migrations.RemoveField(
            model_name='instagramsubscribepage',
            name='crt',
        ),
        migrations.AddField(
            model_name='instagramstatistic',
            name='ctr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CTR'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='ctr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ctr'),
        ),
    ]
