# Generated by Django 3.0.5 on 2021-01-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0008_auto_20201212_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='tiktok_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тикток пиксель'),
        ),
    ]
