# Generated by Django 3.0.5 on 2021-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0011_auto_20210202_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='popup_button_url',
            field=models.TextField(null=True, verbose_name='Ссылка кнопки'),
        ),
    ]
