# Generated by Django 3.0.5 on 2021-02-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0018_auto_20210224_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_color', models.CharField(max_length=50, verbose_name='Первый цвет')),
                ('second_color', models.CharField(max_length=50, verbose_name='Второй цвет')),
            ],
            options={
                'verbose_name': 'Цвет фона',
                'verbose_name_plural': 'Цвета фона',
            },
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='bg_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribe_pages', to='subscribe_pages.BGColor', verbose_name='Цвет фона'),
        ),
    ]
