# Generated by Django 3.0.5 on 2021-02-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0019_auto_20210225_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ISPManager',
        ),
    ]
