# Generated by Django 3.0.5 on 2021-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0024_auto_20210225_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='yandex_pixel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Яндекс пиксель'),
        ),
    ]
