# Generated by Django 3.0.5 on 2021-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0025_instagramsubscribepage_yandex_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgcolor',
            name='text_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Цвет текста'),
        ),
    ]
