# Generated by Django 3.0.5 on 2021-04-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0027_domain_for_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
