# Generated by Django 3.0.5 on 2021-04-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0028_auto_20210408_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramstatistic',
            name='day',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='instagramstatistic',
            name='subscribe_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='subscribe_pages.InstagramSubscribePage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='instagramstatistic',
            name='subscribers',
            field=models.BigIntegerField(default=0, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='instagramstatistic',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
