# Generated by Django 3.0.5 on 2021-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0034_auto_20210427_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscriber',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ник в Instagram'),
        ),
        migrations.AlterField(
            model_name='instagramsubscriber',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP'),
        ),
    ]
