# Generated by Django 3.0.5 on 2021-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0035_auto_20210430_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscriber',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subscribe_pages.InstagramSubscribePage', verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='instagramsubscriber',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='subscribe_pages.InstagramSubscribePage', verbose_name='Просмотры'),
        ),
    ]
