# Generated by Django 3.0.5 on 2021-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0036_auto_20210502_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='roistat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Roistat ID'),
        ),
    ]
