# Generated by Django 3.0.5 on 2021-10-26 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0038_groupofsubscribepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofsubscribepage',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Можно удалить'),
        ),
        migrations.AddField(
            model_name='groupofsubscribepage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='groupofsubscribepage',
            name='subscribe_pages',
        ),
        migrations.AddField(
            model_name='groupofsubscribepage',
            name='subscribe_pages',
            field=models.ManyToManyField(related_name='group', to='subscribe_pages.InstagramSubscribePage', verbose_name='Страницы'),
        ),
    ]
