# Generated by Django 3.0.5 on 2021-11-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0039_auto_20211106_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='enter_login_placeholder',
            field=models.CharField(default='введите ваш логин', max_length=255, verbose_name='Текст "Введите ваш логин"'),
        ),
        migrations.AddField(
            model_name='instagramsubscribepage',
            name='precheck_subscribe_text',
            field=models.CharField(default='Введите ваш логин инстаграма для проверки подписки', max_length=255, verbose_name='Текст "Введите ваш логин инстаграма для проверки подписки"'),
        ),
    ]
