# Generated by Django 3.0.5 on 2021-11-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0041_merge_20211109_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribe_pages', to='subscribe_pages.GroupOfSubscribePage', verbose_name='Группа страниц'),
        ),
    ]
