# Generated by Django 3.0.5 on 2021-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0042_auto_20211110_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofsubscribepage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
