# Generated by Django 3.0.5 on 2021-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0043_auto_20211117_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofsubscribepage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
