# Generated by Django 3.0.5 on 2021-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0046_instagramsubscribepage_single_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsubscriber',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
