# Generated by Django 3.0.5 on 2021-12-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0047_instagramsubscriber_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgcolor',
            name='input_bg_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Фон инпута'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgcolor',
            name='input_text_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Цвет текста инпута'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgcolor',
            name='panel',
            field=models.CharField(default='2C3955', max_length=50, verbose_name='Цвет панели'),
        ),
        migrations.AddField(
            model_name='bgcolor',
            name='panel_icon_bg_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Фон иконки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgcolor',
            name='panel_icon_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Цвет иконки на панели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgcolor',
            name='panel_text_color',
            field=models.CharField(default='#fff', max_length=50, verbose_name='Цвет текста на панели'),
            preserve_default=False,
        ),
    ]
