# Generated by Django 3.0.5 on 2021-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0048_auto_20211222_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgcolor',
            name='input_bg_color',
            field=models.CharField(default='#272C44', max_length=50, verbose_name='Фон инпута'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='input_text_color',
            field=models.CharField(default='#7088AC', max_length=50, verbose_name='Цвет текста инпута'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel',
            field=models.CharField(default='#2C3955', max_length=50, verbose_name='Цвет панели'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_icon_bg_color',
            field=models.CharField(default='#68A4FF45', max_length=50, verbose_name='Фон иконки'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_icon_color',
            field=models.CharField(default='#68A4FF', max_length=50, verbose_name='Цвет иконки на панели'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_text_color',
            field=models.CharField(default='#68A4FF', max_length=50, verbose_name='Цвет текста на панели'),
        ),
    ]
