# Generated by Django 3.0.5 on 2022-03-31 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0055_auto_20220329_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='vksubscribepage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_subscribe_pages', to='subscribe_pages.GroupOfSubscribePage', verbose_name='Группа ВК страниц'),
        ),
        migrations.AlterUniqueTogether(
            name='vksubscription',
            unique_together={('vk_subscriber', 'vk_page')},
        ),
        migrations.CreateModel(
            name='VKGroupOfSubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('can_delete', models.BooleanField(default=True, verbose_name='Можно удалить')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_group_of_pages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа ВК страницы',
                'verbose_name_plural': 'Группы ВК страниц',
            },
        ),
    ]
