# Generated by Django 3.0.5 on 2022-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0057_auto_20220331_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vksubscriber',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='vksubscriber',
            name='sex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пол'),
        ),
    ]
