# Generated by Django 3.0.5 on 2022-04-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0060_auto_20220414_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='vksubscribepage',
            name='type_group_id',
            field=models.CharField(choices=[('id', 'id'), ('slug', 'slug')], default='id', max_length=10, verbose_name='Тип id группы'),
        ),
    ]
