# Generated by Django 3.0.5 on 2022-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0064_auto_20221103_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='present_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
