# Generated by Django 3.0.5 on 2022-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0071_auto_20221110_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ МАТЕРИАЛЫ', max_length=30, verbose_name='Текст на кнопке'),
        ),
    ]
