# Generated by Django 3.0.5 on 2022-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0073_auto_20221110_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ', max_length=30, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
