# Generated by Django 3.0.5 on 2022-11-10 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe_pages', '0074_auto_20221110_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='tg_bot_url',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='tg_channel_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrams', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
