# Generated by Django 3.0.5 on 2022-11-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0075_auto_20221110_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='title',
        ),
    ]
