# Generated by Django 3.0.5 on 2022-11-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0076_auto_20221110_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='button_text',
        ),
    ]
