# Generated by Django 3.0.5 on 2022-11-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0079_auto_20221111_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='button_text',
        ),
    ]
