# Generated by Django 3.0.5 on 2022-11-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0080_remove_telegramsubscribepage_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscribepage',
            name='title',
        ),
    ]
