# Generated by Django 3.0.5 on 2022-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0082_telegramsubscribepage_message_after_getting_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='bot_button_text',
            field=models.CharField(default='', max_length=500, verbose_name='Текст на кнопке (бот)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='bot_button_url',
            field=models.URLField(default='', verbose_name='Ссылка кнопки (бот)'),
            preserve_default=False,
        ),
    ]
