# Generated by Django 3.0.5 on 2022-11-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0087_auto_20221122_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='is_linked',
            field=models.BooleanField(default=False, verbose_name='Привязан'),
        ),
    ]
