# Generated by Django 3.0.5 on 2022-11-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0088_auto_20221122_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='can_get_material',
            field=models.BooleanField(default=False, verbose_name='Может просматривать материал'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='ip',
            field=models.CharField(default='8.8.8.8', max_length=255, verbose_name='IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subscribe_pages.TelegramSubscribePage', verbose_name='Подписки'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='subscribe_pages.TelegramSubscribePage', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='bot_button_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки (бот)'),
        ),
        migrations.CreateModel(
            name='TelegramStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('subscribers', models.BigIntegerField(default=0, verbose_name='Подписки')),
                ('ctr', models.FloatField(blank=True, default=0, null=True, verbose_name='CTR')),
                ('subscribe_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='subscribe_pages.TelegramSubscribePage', verbose_name='Страница Telegram')),
            ],
            options={
                'verbose_name': 'Статистика Telegram',
                'verbose_name_plural': 'Статистики Telegram',
                'ordering': ('subscribe_page',),
            },
        ),
    ]
