# Generated by Django 3.0.5 on 2022-11-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0089_auto_20221124_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'verbose_name': 'Telegram Подписчик', 'verbose_name_plural': 'Telegram Подписчики'},
        ),
    ]
