# Generated by Django 3.0.5 on 2022-11-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0090_auto_20221124_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramstatistic',
            options={'ordering': ('telegram_subscribe_page',), 'verbose_name': 'Статистика Telegram', 'verbose_name_plural': 'Статистики Telegram'},
        ),
        migrations.RenameField(
            model_name='telegramstatistic',
            old_name='subscribe_page',
            new_name='telegram_subscribe_page',
        ),
    ]
