# Generated by Django 3.0.5 on 2022-11-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0091_auto_20221124_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscriber',
            name='telegram_subscribe_page',
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe_pages.TelegramUser'),
        ),
    ]
