# Generated by Django 3.0.5 on 2022-11-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0092_auto_20221124_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscriber',
            name='subscribe_to',
        ),
        migrations.RemoveField(
            model_name='telegramsubscriber',
            name='views',
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='telegram_subscribe_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscriber', to='subscribe_pages.TelegramSubscribePage', verbose_name='Подписная Telegram страница'),
        ),
    ]
