# Generated by Django 3.0.5 on 2022-11-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0095_auto_20221125_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='page_hash',
            field=models.CharField(default='de650a3f0415fa3976b64e6531125f9a931d9badd2785dafccfe8efce681c0a5', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='popup_button_text',
            field=models.CharField(default='ПОЛУЧИТЬ МАТЕРИАЛЫ', max_length=19, verbose_name='Текст на кнопке (подписная страница)'),
        ),
    ]
