# Generated by Django 3.0.5 on 2022-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0096_auto_20221129_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscriber',
            name='telegram_subscribe_page',
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subscribe_pages.TelegramSubscribePage', verbose_name='Подписки'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='subscribe_pages.TelegramSubscribePage', verbose_name='Просмотры'),
        ),
    ]
