# Generated by Django 3.0.5 on 2022-12-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221204_1744'),
        ('subscribe_pages', '0097_auto_20221129_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscribepage',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscribe_pages', to='api.TelegramBotUser'),
        ),
    ]
