# Generated by Django 3.0.5 on 2022-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0100_auto_20221205_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_chat_id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_tg_users', to='subscribe_pages.TelegramSubscribePage', verbose_name='Подписки'),
        ),
    ]
