# Generated by Django 3.0.5 on 2022-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0102_auto_20221207_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgcolor',
            name='success_page_bg_color',
            field=models.CharField(default='#32405e', max_length=50, verbose_name='Цвет заднего фона на странице благодарности за подписку'),
        ),
    ]
