# Generated by Django 3.0.5 on 2022-12-10 03:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0103_bgcolor_success_page_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgcolor',
            name='panel',
            field=colorfield.fields.ColorField(default='#2C3955', image_field=None, max_length=18, samples=None, verbose_name='Цвет панели'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='success_page_bg_color',
            field=colorfield.fields.ColorField(default='#32405e', image_field=None, max_length=18, samples=None, verbose_name='Цвет заднего фона на странице благодарности за подписку'),
        ),
    ]
