# Generated by Django 3.0.5 on 2022-12-10 03:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_pages', '0104_auto_20221210_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgcolor',
            name='first_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Первый цвет'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='input_bg_color',
            field=colorfield.fields.ColorField(default='#272C44', image_field=None, max_length=18, samples=None, verbose_name='Фон инпута'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='input_text_color',
            field=colorfield.fields.ColorField(default='#7088AC', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста инпута'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_icon_bg_color',
            field=colorfield.fields.ColorField(default='#68A4FF45', image_field=None, max_length=18, samples=None, verbose_name='Фон иконки'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_icon_color',
            field=colorfield.fields.ColorField(default='#68A4FF', image_field=None, max_length=18, samples=None, verbose_name='Цвет иконки на панели'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='panel_text_color',
            field=colorfield.fields.ColorField(default='#68A4FF', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста на панели'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='second_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Второй цвет'),
        ),
        migrations.AlterField(
            model_name='bgcolor',
            name='text_color',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста'),
        ),
    ]
