# Generated by Django 3.0.5 on 2022-12-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlreadySubscribedChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('telegram_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='api.TelegramUsers')),
            ],
        ),
    ]
