# Generated by Django 3.0.5 on 2022-12-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alreadysubscribedchannels',
            old_name='telegram_users',
            new_name='telegram_user',
        ),
    ]
