# Generated by Django 3.0.5 on 2022-12-02 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221202_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alreadysubscribedchannels',
            name='telegram_user',
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='telegram_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='api.AlreadySubscribedChannels'),
            preserve_default=False,
        ),
    ]
