# Generated by Django 3.0.5 on 2022-12-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221202_0310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUsers',
            new_name='TelegramUser',
        ),
    ]
