# Generated by Django 3.0.5 on 2022-12-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221202_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_channel',
        ),
        migrations.DeleteModel(
            name='AlreadySubscribedChannels',
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='api.TelegramUser'),
        ),
    ]
