# Generated by Django 3.0.5 on 2021-04-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_referrer_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='promocode_used',
        ),
    ]
