# Generated by Django 3.0.5 on 2021-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210408_0740'),
    ]

    operations = [
    ]
