# Generated by Django 3.0.5 on 2021-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211101_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='white', max_length=15, verbose_name='Тема'),
        ),
    ]
