# Generated by Django 3.0.5 on 2022-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_subscribe_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='button_text',
            field=models.CharField(default='ПОЛУЧИТЬ', max_length=500, verbose_name='Текст на кнопке (бот)'),
        ),
        migrations.AlterField(
            model_name='telegramsubscribepage',
            name='popup_title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
