# Generated by Django 3.0.5 on 2020-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitpay_id', models.IntegerField(null=True, verbose_name='UnitPay ID')),
                ('project_id', models.IntegerField(null=True, verbose_name='Project ID')),
                ('account', models.CharField(max_length=255, null=True, verbose_name='Account')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('bonus', models.IntegerField(default=0, verbose_name='Bonus')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
