# Generated by Django 3.0.5 on 2020-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201204_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_id',
            field=models.CharField(default='299571', max_length=255, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unitpay_id',
            field=models.CharField(default='299571-dd2a7', max_length=255, null=True, verbose_name='UnitPay ID'),
        ),
    ]
