# Generated by Django 3.0.5 on 2021-08-04 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0007_auto_20210528_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_id',
            field=models.CharField(default='431789', max_length=255, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unitpay_id',
            field=models.CharField(default='431789-4b7e1', max_length=255, null=True, verbose_name='UnitPay ID'),
        ),
        migrations.CreateModel(
            name='OrderCent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(null=True, verbose_name='Идентификатор платежа')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('order_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('order_currency', models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=5, verbose_name='Курс')),
                ('cent_bill_id', models.CharField(max_length=255, null=True)),
                ('bonus', models.IntegerField(default=0, verbose_name='Бонус')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cent_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Cent Заказ',
                'verbose_name_plural': 'Cent Заказы',
            },
        ),
    ]
