# Generated by Django 3.0.5 on 2020-12-03 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='order_currency',
            field=models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=5, verbose_name='Order currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Order sum'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Account'),
        ),
    ]
