# Generated by Django 3.0.5 on 2021-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.UUIDField(null=True, verbose_name='Идентификатор'),
        ),
    ]
